version:
  @project.version@
name:
  @project.name@

server:
  servlet:
    context-path: /api
  port: 8093

spring:
  profiles:
    active: compose
  application:
    name: adsManager
  config:
    import: classpath:messages.yml
  flyway:
    enabled: true
    locations: classpath:db/migration



