spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ad_data
    username: root
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        generate_statistics: true
  docker:
    compose:
      enabled: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  redis-new:
    port: 6379
    host: localhost

cache:
  expiration:
    default: 3600


###############################################################################
# logging
###############################################################################
logging:
  file:
    name: /app/logs/adsManager/${spring.application.name}.log
  logback:
    rollingpolicy:
      file-name-pattern: /app/logs/adsManager/${spring.application.name}.%d{yyyy-MM-dd}.%i.log
